// Combines the data from multiple parsing trees into one object.
// data: an array containing data from different parsers, generated by the async library. Each item in the array is an object containing the output of a single parser.
module.exports = function(tree) {
  var newTree = {};

  for (var i in tree) {
    newTree[i] = {
      title: tree[i].title,
      description: tree[i].description,
      docs: tree[i].docs,
      fileName: tree[i].fileName
    }

    // Process Sass
    if (tree[i].sass) {
      newTree[i].sass = {
        variable: [],
        mixin: [],
        'function': []
      }

      for (var j in tree[i].sass) {
        var obj = tree[i].sass[j];
        newTree[i].sass[obj.context.type].push(obj);
      }
    }
  }

  return newTree;
}